services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres-${ENV_LABEL}
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 2s
            timeout: 1s
            retries: 30
            start_period: 10s
        networks:
            - app-network

    prisma-studio:
        container_name: prisma-studio-${ENV_LABEL}
        build:
            context: ../
            dockerfile: docker/Dockerfile.prisma-studio
            args:
                - DATABASE_URL=${DATABASE_URL}
        environment:
            - DATABASE_URL=${DATABASE_URL}
        ports:
            # Requires SSH tunnel on port 5555
            - "127.0.0.1:5555:5555"
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network

    nextjs:
        container_name: nextjs-${ENV_LABEL}
        env_file:
            - ../.env.basic
        build:
            context: ../
            args:
                - NODE_ENV=${NODE_ENV}
                - NEXTJS_STANDALONE=${NEXTJS_STANDALONE}
                - DATABASE_URL=${DATABASE_URL}
                - POSTGRES_HOST=${POSTGRES_HOST}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                - POSTGRES_DB=${POSTGRES_DB}
                - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
            dockerfile: docker/Dockerfile
            target: runner
        ports:
            - "3000:3000"
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network

volumes:
    postgres-volume:
        name: postgres-volume-${ENV_LABEL}
        driver: local

networks:
    app-network:
        name: app-network-${ENV_LABEL}
        driver: bridge
